apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd
  template:
    metadata:
      labels:
        app: ci-cd
    spec:
      containers:
      - name: gpt-description-generator
        image: khaliddestiawan/gpt-description-generator:latest
        ports:
        - containerPort: 5001